services:
    database:
        image: postgres:13
        environment:
            POSTGRES_DB: chatapp
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        ports:
            - "5432:5432"
        volumes:
            - ./database:/var/lib/postgresql/data
